# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Haverhill Hackspace
email: info@haverhillhack.space
description: > # this means to ignore newlines until "baseurl:"
  Haverhill Hackspace - Collaborative coworking in downtown Haverhill. Daily,
  weekly, and monthly memberships available.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://haverhillhack.space" # the base hostname & protocol for your site
twitter_username: haverhillhack
facebook_username: haverhillhackspace

# Build settings
markdown: kramdown
